CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);

ALTER TABLE IF EXISTS users RENAME COLUMN IF EXISTS name TO username;
ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS email;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password_hash TEXT;
